trigger:
  branches:
    exclude:
      - '*'
    include:
      - 'release/*'

pr:  
  branches:
   include:
     - release/*
 
  paths:
   include:
     - 'src/GetTrainsFunction/*'
   exclude:
     - README.md

  drafts: false

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''


steps:
  - task: UseDotNet@2
    inputs:
      version: '8.x'
      includePreviewVersions: true # Required for preview versions

  - script: git fetch --unshallow
    displayName: 'Fetch Full History'

  - task: UseGitVersion@5
    displayName: 'Get Version'
    inputs:
      versionSpec: '5.x'

  - task: DotNetCoreCLI@2
    displayName: 'Build and Publish'
    inputs:
      command: publish
      arguments: '--configuration $(buildConfiguration) /p:Version=$(GitVersion.AssemblySemVer) --output publish_output'
      projects: 'src/GetTrainsFunction/GetTrainsFunction.csproj'
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false

  - task: DotNetCoreCLI@2
    displayName: 'Run xUnit tests with code coverage'
    inputs:
      command: test
      projects: 'test/GetTrainsFunction.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
      publishTestResults: true


  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage report'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/GetTrainFunction_v$(GitVersion.MajorMinorPatch).zip"

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/GetTrainFunction_v$(GitVersion.MajorMinorPatch).zip'
      ArtifactName: 'drop'
