trigger:
  branches:
    exclude:
      - '*'
pr:  
  branches:
   include:
     - release/*
   sourceBranch:
     - refs/heads/release/*
   targetBranch:
     - refs/heads/release/*
 
  paths:
   include:
     - 'src/GetTrainsFunction/*'
   exclude:
     - README.md

  drafts: false
  

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'


steps:
  - task: UseDotNet@2
    inputs:
      version: '8.x'
      includePreviewVersions: true # Required for preview versions

  - script: git fetch --unshallow
    displayName: 'Fetch Full History'

  - task: CmdLine@2
    displayName: 'Install GitVersion'
    inputs:
      script: 'dotnet tool install --global GitVersion.Tool --version 5.10.0'

  - task: CmdLine@2
    displayName: 'Generate Version'
    inputs:
      script: 'dotnet-gitversion /output buildserver /nofetch'

  - powershell: |
      $version = $(GitVersion.MajorMinorPatch)
      $csprojPath = 'src/GetTrainsFunction/GetTrainsFunction.csproj'
      $csprojContent = Get-Content $csprojPath
      $csprojContent -replace '<Version>.*</Version>', "<Version>$(GitVersion.MajorMinorPatch)</Version>" | Set-Content $csprojPath
    displayName: 'Update .csproj File'

  - script: |
     git config --global user.email "navneet.hegde@hotmail.com"
     git config --global user.name "Navneet Hegde"
    displayName: 'Set Git Config'

  - script: git add .
    displayName: 'Stage Changes'

  - script: git commit -m "Update version to $(GitVersion.MajorMinorPatch)"
    displayName: 'Commit Changes'

  - task: DotNetCoreCLI@2
    displayName: 'Build and Publish'
    inputs:
      command: publish
      arguments: '--configuration $(buildConfiguration) --output publish_output'
      projects: 'src/GetTrainsFunction/GetTrainsFunction.csproj'
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false

  - task: DotNetCoreCLI@2
    displayName: 'Run xUnit tests with code coverage'
    inputs:
      command: test
      projects: 'test/GetTrainsFunction.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
      publishTestResults: true


  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage report'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/build$(GitVersion.MajorMinorPatch).zip"

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(GitVersion.MajorMinorPatch).zip'
      ArtifactName: 'drop'
